name: jwt_rbac_flutter
description: Projeto de autenticação JWT + RBAC em Flutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Requisições HTTP
  dio: ^5.7.0

  # Armazenamento seguro (tokens, senhas, etc.)
  flutter_secure_storage: ^9.2.2

  # Gerenciamento de estado (opcional, caso queira melhorar depois)
  provider: ^6.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
